language: android
jdk: oraclejdk8
# Use the Travis Container-Based Infrastructure
sudo: false

env:
  global:
    #- ANDROID_TARGET=android-22
    #- ANDROID_ABI=armeabi-v7a
    - ANDROID_API_LEVEL=25
    - EMULATOR_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=25.0.0
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # Specify both versions to resolve issue with missing image from google repository
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    - build-tools-25.0.0
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    # Image 23 might be missing from google repository
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_install:
  - chmod +x gradlew
  # add configuration to see Tavis report  on codacy
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly


script:
  - chmod +x ./gradlew
  - ./gradlew build
  - ./gradlew connectedAndroidTest coveralls
  #- ./gradlew jacocoTestReport coveralls


notifications:
    email: false

